// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_update_z
Rcpp::NumericMatrix cpp_update_z(const Rcpp::NumericMatrix& Y_r, const Rcpp::NumericMatrix& nuisance_r, const Rcpp::NumericMatrix& L0_r, const Rcpp::NumericVector& B, const Rcpp::NumericVector& Delta, const Rcpp::NumericMatrix& D_r, const Rcpp::IntegerVector& donor, const double ridge, const int threads);
RcppExport SEXP _ReGIFT_cpp_update_z(SEXP Y_rSEXP, SEXP nuisance_rSEXP, SEXP L0_rSEXP, SEXP BSEXP, SEXP DeltaSEXP, SEXP D_rSEXP, SEXP donorSEXP, SEXP ridgeSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type Y_r(Y_rSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type nuisance_r(nuisance_rSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type L0_r(L0_rSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type D_r(D_rSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type donor(donorSEXP);
    Rcpp::traits::input_parameter< const double >::type ridge(ridgeSEXP);
    Rcpp::traits::input_parameter< const int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_update_z(Y_r, nuisance_r, L0_r, B, Delta, D_r, donor, ridge, threads));
    return rcpp_result_gen;
END_RCPP
}
// cpp_update_z_blocked
Rcpp::NumericMatrix cpp_update_z_blocked(const Rcpp::NumericMatrix& Y, const Rcpp::NumericMatrix& nuisance, const Rcpp::NumericMatrix& L0, const Rcpp::NumericVector& B, const Rcpp::NumericVector& Delta, const Rcpp::NumericMatrix& D, const Rcpp::IntegerVector& donor, const int gene_block, const double ridge, const int threads);
RcppExport SEXP _ReGIFT_cpp_update_z_blocked(SEXP YSEXP, SEXP nuisanceSEXP, SEXP L0SEXP, SEXP BSEXP, SEXP DeltaSEXP, SEXP DSEXP, SEXP donorSEXP, SEXP gene_blockSEXP, SEXP ridgeSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type nuisance(nuisanceSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type L0(L0SEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type D(DSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type donor(donorSEXP);
    Rcpp::traits::input_parameter< const int >::type gene_block(gene_blockSEXP);
    Rcpp::traits::input_parameter< const double >::type ridge(ridgeSEXP);
    Rcpp::traits::input_parameter< const int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_update_z_blocked(Y, nuisance, L0, B, Delta, D, donor, gene_block, ridge, threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ReGIFT_cpp_update_z", (DL_FUNC) &_ReGIFT_cpp_update_z, 9},
    {"_ReGIFT_cpp_update_z_blocked", (DL_FUNC) &_ReGIFT_cpp_update_z_blocked, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_ReGIFT(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
