# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_update_z <- function(Y_r, nuisance_r, L0_r, B, Delta, D_r, donor, ridge = 1e-6, threads = 1L) {
    .Call(`_ReGIFT_cpp_update_z`, Y_r, nuisance_r, L0_r, B, Delta, D_r, donor, ridge, threads)
}

cpp_update_z_blocked <- function(Y, nuisance, L0, B, Delta, D, donor, gene_block = 256L, ridge = 1e-6, threads = 1L) {
    .Call(`_ReGIFT_cpp_update_z_blocked`, Y, nuisance, L0, B, Delta, D, donor, gene_block, ridge, threads)
}

